### ISSUE TITLE
Old reference

### ISSUE THREAD

**Issue by kagflores** [learn-co-curriculum/html-lists-lab#10]
The description makes reference to a list of months while the examples are lists of food.
"To make a list, we write out the opening and closing <ul> tags, and inside them, we'll add <li> tags, each listing a single month."

**Comment by rrcobb** [comment]
good catch, addressed in https://github.com/learn-co-curriculum/html-lists-lab/commit/8a83d41bbce5cd4e85ff25d399cfa5705ee38f4d
