### ISSUE TITLE
Missing <ul> & </ul> tags in UL 

### ISSUE THREAD

**Issue by merecka** [learn-co-curriculum/html-lists-lab#9]
In the following example used in the lab for discussing Unordered Lists and Nested Lists, it appears as though you are missing a "ul" & "/ul" for the nested list of Snacks.

<ul>
  <li>Sandwiches
    <ul>
      <li>Ham and Cheese</li>
      <li>Grilled Cheese</li>
    </ul>
  </li>
  <li>Snacks
    <li>Nacho Cheese French Fries</li>
    <li>Cheese and crackers</li>
  </li>
  <li>Soups
    <ul>
      <li>Cheese soup</li>
    </ul>
  </li>
  <li>Sushi
    <ul>
      <li>Spicy Salmon Rolls</li>
      <li>California Rolls</li>
    </ul>
  </li>
</ul>

**Comment by rrcobb** [comment]
Thanks, fixed!
